name: Build & Test

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore WeatherApplication

      - name: Build
        run: dotnet build WeatherApplication --configuration Release --no-restore

      - name: Test
        run: dotnet test WeatherApplication --configuration Release --no-build
